---

- name: Add {{ os_group }} group
  group:
    name: "{{ os_group }}"
    state: present  
  become: yes  

- name: Add {{ os_user }} user
  user:
    name: "{{ os_user }}"
    group: "{{ os_group }}"
    home: /home/{{ os_user }}
    shell: /bin/bash
    comment: Splunk User
  become: yes

- name: Create {{ splunk_home }} dir
  file:
    path: "{{ splunk_home }}"
    state: directory
    mode: 0755  
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes

- name: Download (wget) {{ splunk_tgz }}
  get_url:
    url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version={{ splunk_version }}&product=splunk&filename={{ splunk_tgz }}&wget=true
    checksum: "{{ splunk_tgz_checksum_alg }}:{{ splunk_tgz_checksum }}"
    dest: /home/{{ os_user }}
    mode: 0640  
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes

- name: Extract {{ splunk_tgz }} to {{ splunk_home }}
  unarchive:
    src: /home/{{ os_user }}/{{ splunk_tgz }}
    dest: "{{ splunk_home }}/.."
    remote_src: yes
  become: yes

- name: Create user-seed.conf file for default admin creds
  template:
    src: user-seed.conf.j2
    dest: "{{ splunk_home }}/etc/system/local/user-seed.conf"
  become: yes

- name: Set {{ splunk_home }} owner & group recursively
  file:
    path: "{{ splunk_home }}"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
    recurse: yes
  become: yes  

- name: Start Splunk for the first time (initd method)
  command: "{{ splunk_home }}/bin/splunk start --no-prompt --answer-yes --accept-license"
  become: yes  
  become_user: "{{ os_user }}"
  when: install_method == "initd"

- name: Splunk enable boot-start
  command: "{{ splunk_home }}/bin/splunk enable boot-start -user {{ os_user }} --no-prompt --answer-yes --accept-license"
  become: yes  

- name: Start Splunk for the first time (systemd method)
  command: "systemctl start Splunkd"
  become: yes
  when: install_method == "systemd"
  
- name: "Create symlink to splunk in /usr/local/bin"
  file:
    src: "{{ splunk_home }}/bin/splunk"
    path: /usr/local/bin/splunk
    state: link
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes