---

- name: Add {{ os_group }} group
  group:
    name: "{{ os_group }}"
    state: present  
  become: yes  

- name: Add {{ os_user }} user
  user:
    name: "{{ os_user }}"
    group: "{{ os_group }}"
    home: /home/{{ os_user }}
    shell: /bin/bash
    comment: Splunk User
  become: yes

- name: Create {{ splunk_home }} dir
  file:
    path: "{{ splunk_home }}"
    state: directory
    mode: 0755  
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes

- name: Check for the presence of /home/{{ os_user }}/{{ splunk_tgz }}
  stat: 
    path: /home/{{ os_user }}/{{ splunk_tgz }}
    get_checksum: yes  
    checksum_algorithm: md5
  register: splunk_tgz_downloaded_flag
  become: yes

- name: Download (wget) {{ splunk_tgz }}
  get_url:
    url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version={{ splunk_version }}&product=splunk&filename={{ splunk_tgz }}&wget=true
    checksum: "{{ splunk_tgz_checksum_alg }}:{{ splunk_tgz_checksum }}"
    dest: /home/{{ os_user }}
    mode: 0640  
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes
  when: splunk_tgz_downloaded_flag.stat.exists == False

- name: Extract {{ splunk_tgz }} to {{ splunk_home }}
  unarchive:
    src: /home/{{ os_user }}/{{ splunk_tgz }}
    dest: "{{ splunk_home }}/.."
    remote_src: yes
  become: yes

- name: Create user-seed.conf file for default admin creds
  template:
    src: user-seed.conf.j2
    dest: "{{ splunk_home }}/etc/system/local/user-seed.conf"
  become: yes

- name: "Touch {{ splunk_home }}/etc/.ui_login"
  file:
    path: "{{ splunk_home }}/etc/.ui_login"
    state: touch
    mode: '0644'
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes  

- name: Set {{ splunk_home }} owner & group recursively
  file:
    path: "{{ splunk_home }}"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
    recurse: yes
  become: yes  

- name: -initd- Start Splunk for the first time
  command: "{{ splunk_home }}/bin/splunk start --no-prompt --answer-yes --accept-license"
  become: yes  
  become_user: "{{ os_user }}"
  when: install_method == "initd"

- name: -initd & Splunk 7.2.1 or earlier- Splunk enable boot-start
  command: "{{ splunk_home }}/bin/splunk enable boot-start -user {{ os_user }} --no-prompt --answer-yes --accept-license"
  become: yes  
  when: 
    - install_method == "initd" 
    - splunk_version is version('7.2.1', '<=')

- name: -initd & Splunk 7.2 or later- Splunk enable boot-start
  command: "{{ splunk_home }}/bin/splunk enable boot-start -systemd-managed 0 -user {{ os_user }} --no-prompt --answer-yes --accept-license"
  become: yes  
  when: 
    - install_method == "initd" 
    - splunk_version is version('7.2.0', '>=')

- name: -systemd & Splunk 7.2.2 to 7.2.x- Splunk enable boot-start (no systemd arguments added)
  command: "{{ splunk_home }}/bin/splunk enable boot-start -user {{ os_user }} --no-prompt --answer-yes --accept-license"
  become: yes  
  when:
    - install_method == "systemd" 
    - splunk_version is version('7.2.2', '>=')
    - splunk_version is version('7.3', '<')

- name: -systemd & Splunk 7.3 or later- Splunk enable boot-start (-systemd-managed 1)
  command: "{{ splunk_home }}/bin/splunk enable boot-start -systemd-managed 1 -user {{ os_user }} --no-prompt --answer-yes --accept-license"
  become: yes 
  when:
    - install_method == "systemd" 
    - splunk_version is version('7.3', '>=')

- name: -systemd & Ubuntu- Fix the /etc/systemd/system/Splunkd.service file for Ubuntu support
  replace:
    path: /etc/systemd/system/Splunkd.service
    regexp: '\/init.scope'
    replace: ''
  become: yes 
  when: 
    - install_method == "systemd"  
    - ansible_distribution == "Ubuntu"  

- name: -systemd & Ubuntu- After Splunkd.service update reload the systemd daemon units
  command: systemctl daemon-reload
  become: yes 
  when: 
    - install_method == "systemd"  
    - ansible_distribution == "Ubuntu"    

- name: -systemd- Start Splunk for the first time
  command: "systemctl start Splunkd"
  become: yes
  when: 
    - install_method == "systemd"
  
- name: "Create symlink to splunk in /usr/local/bin"
  file:
    src: "{{ splunk_home }}/bin/splunk"
    path: /usr/local/bin/splunk
    state: link
    owner: "{{ os_user }}"
    group: "{{ os_group }}"
  become: yes